### ISSUE TITLE
Doesn't transition on autofill

### ISSUE THREAD

**Issue by ianobermiller** [ENFOS/FlowupLabels.js#2]
Autofilling the form using e.g. Lastpass doesn't cause the labels to transition.

**Comment by TheSisb** [comment]
Have you set the onInitLoad parameter to true?  I have it disabled by default since not everyone might need it.

``` js
$('.FlowupLabels').FlowupLabels({
        feature_onInitLoad: true
});
```

[edit] Sorry, I get it now.  Working on a fix.

**Comment by ianobermiller** [comment]
I should have clarified. This was reproduced on the demo page.

**Comment by TheSisb** [comment]
Having done some research, it seems JavaScript is unable to detect auto-filling of fields due to security concerns.  The only way to implement this in JavaScript is then to create a setInterval loop which keeps running ever few milliseconds to see if anything has changed.  However, that is simply unacceptable for performance reasons. 
I have another idea which may work using only CSS.  It may also address the graceful degradation issue.  I'll try to work on it today or latest tomorrow (Thanksgiving is a busy day).

**Comment by TheSisb** [comment]
So here's what I thought of, since you cannot detect field autofilling:

1- Start labels in their raised state.  Descend them to the normal state if the field is empty on page load (without animation so it's quicker).  This handles graceful degradation, but doesn't handle cases where fields get auto-filled after the page has loaded for some time.

2- A 500ms setInterval to constantly poll for field values that turns off after the user fills in a single field.  This can make a page really slow.

3- Set autocomplete="off" on form fields. (I don't recommend this unless you're sure about why you want to do this, like a sign up form or something, maybe.)

I'm afraid there are no solid solutions that work for tools like LastPass. If I'm missing anything please do share.
