### ISSUE TITLE
Doesn't work for autofills

### ISSUE THREAD

**Issue by riliwanrabo** [ENFOS/FlowupLabels.js#7]
Tested on chrome, it doesn't go well with autofills, label and values stay on themselves
![fltest](https://cloud.githubusercontent.com/assets/6854815/5215296/29492342-7626-11e4-8737-451abddf9ff1.jpg)

**Comment by TheSisb** [comment]
Please review https://github.com/ENFOS/FlowupLabels.js/issues/2
Let me know if you have any new ideas.  

This form design works best for form fields that you are confident won't be autofilled or on simple pages where you can get away with doing a "setInterval".

**Comment by TheSisb** [comment]
I've also updated the code to make "feature_onLoadInit" default to true

**Comment by hovatterz** [comment]
``` javascript
      // On page load, make sure it looks good
      if (settings.feature_onLoadInit) {
        setTimeout(function() {
          $scope.find('input').trigger('blur.flowupLabelsEvt');
        }, 250);
      }
```

This works for me. Fixes the label for fields being populated by the browser (saved passwords and etc) as well as having inputs with pre-filled values. Just thought I'd share.

**Comment by TheSisb** [comment]
@hovatterz Your solution works for some cases, but not all.  If a password manager takes longer than 250ms to fill the form or if it prompts the user first then we're back at square one.  I'd rather keep the partial fix out of the code so that developers don't get surprised by this issue too late in development.

I appreciate your suggestion though! Thanks.

**Comment by hovatterz** [comment]
Certainly. I wasn't too concerned with password managers and etc. Was just a fix for that specific issue I was having. Thanks for all the work on this!
